image: node:14.17.0

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: louisadamian.com
  SECURE_LOG_LEVEL: error

stages:
  - dev
  - test
  - build
  - deploy
  - dast

dast:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  stage: dast
  dast_configuration:
    site_profile: "louisadamian.com"
    scanner_profile: "main_scanner"

build:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
    - public

deploys3:
  stage: deploy
  image: "python:latest"
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
      name: ${CI_COMMIT_REF_SLUG}
      action: stop
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
