# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:14.17.0
include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: error
pages:
  stage: deploy
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn build
  - mkdir public
  - mv .vuepress/dist public
  artifacts:
    paths:
    - public
  only:
  - master
stages:
- test
sast:
  stage: test
