image: node:14.17.0

#build-job:
#  stage: build
#  script:
#  - yarn install
#  - yarn build
#  only:
#  - master

pages:
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn build
  stage: deploy
  artifacts:
    paths:
    - public
  only:
  - master
