image: node:16.17.0

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test
  - deploy
  - dast

dast:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: dast
  dast_configuration:
    site_profile: louisadamian.com
    scanner_profile: main_scanner

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"