image: node:14.17.0

include:
  - template: Dependency-Scanning.gitlab-ci.yml
variables:
      SECURE_LOG_LEVEL: error

pages:
  stage: deploy
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn build
  - mkdir public
  - mv .vuepress/dist public
  artifacts:
    paths:
    - public
  only:
  - master
