# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:14.17.0
include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: DAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
variables:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: louisadamian.com
  SECURE_LOG_LEVEL: error
stages:
- dev
- build
- test
- deploy
- dast
dast:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
  stage: dast
  dast_configuration:
    site_profile: louisadamian.com
    scanner_profile: main_scanner
build:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
    - public

deployS3:
  stage: deploy
  image: python:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  before_script:
  - pip install awscli
  - aws configure set region us-east-1 --profile integ
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} --profile integ
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} --profile integ
  script:
  - aws s3 cp public s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: "${CI_COMMIT_REF_SLUG}"
    url: http://${BUCKET_NAME}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}
    on_stop: cleanS3

cleanS3:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual
